### ISSUE TITLE
Not able to run on NVIDIA K80 - Out of memory

### ISSUE THREAD

**Issue by pavitrakumar78** [rdcolema/nc-fish-classification#3]
Hi,

I have been trying to run your code on a p2.xlarge instance which has a NVIDIA K80 GPU (12GB VRAM), but when I run the script, I get an out of memory error. This is confusing because if you were able to run the same code on a 980m which has 8GB VRAM, running the code on K80 shouldn't be a probelm. I have also not allocated any cnmem. Do you have any theano specific params you used to run this on your system with  nvidia 980m?

As per the log attached below, immediately after running the code, only 200mb remain in GPU. Why does this happen?

Also, I was not sure what you meant by `train_full` and `train` in your code, so I just renamed the `train_full` to `train`. `train` folder has the same data (8 folders with images inside) as the one posted on kaggle with no modifications. 

```
Using Theano backend.
Couldn't import dot_parser, loading of dot files will not be possible.
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: Tesla K80 (CNMeM is disabled, cuDNN 5105)
Starting Training Run 1 of 5...

Training vggbn model...

/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:621: UserWarning: `output_shape` argument not specified for layer lambda_1 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 3, 270, 480)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
Found 3777 images belonging to 8 classes.
Epoch 1/10
Error allocating 1006632960 bytes of device memory (out of memory). Driver report 295436288 bytes free and 11995578368 bytes total 
Traceback (most recent call last):
  File "ensemble_Model.py", line 92, in <module>
    model_paths = train_all()
  File "ensemble_Model.py", line 86, in train_all
    model_path = train(model, model_str)
  File "ensemble_Model.py", line 63, in train
    parent_model.fit_full(full_train_path, nb_trn_samples=nb_full_train_samples, nb_epoch=nb_epoch, aug=nb_aug)
  File "/home/ubuntu/nc-fish-classification/models.py", line 130, in fit_full
    callbacks=callbacks)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 935, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1553, in fit_generator
    class_weight=class_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1316, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 959, in __call__
    return self.function(*inputs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
MemoryError: Error allocating 1006632960 bytes of device memory (out of memory).
Apply node that caused the error: GpuElemwise{Composite{(i0 * sqr(i1))},no_inplace}(CudaNdarrayConstant{[[ 0.05]]}, GpuDot22.0)
Toposort index: 569
Inputs types: [CudaNdarrayType(float32, (True, True)), CudaNdarrayType(float32, matrix)]
Inputs shapes: [(1, 1), (61440, 4096)]
Inputs strides: [(0, 0), (4096, 1)]
Inputs values: [CudaNdarray([[ 0.05]]), 'not shown']
Outputs clients: [[GpuElemwise{Composite{((i0 * sqrt(clip((i1 + i2), i3, i4))) / sqrt(clip((i1 + i5 + i6), i3, i4)))},no_inplace}(GpuDot22.0, CudaNdarrayConstant{[[  9.99999994e-09]]}, <CudaNdarrayType(float32, matrix)>, CudaNdarrayConstant{[[ 0.]]}, CudaNdarrayConstant{[[ inf]]}, GpuElemwise{mul,no_inplace}.0, GpuElemwise{Composite{(i0 * sqr(i1))},no_inplace}.0), GpuElemwise{Add}[(0, 1)](GpuElemwise{mul,no_inplace}.0, GpuElemwise{Composite{(i0 * sqr(i1))},no_inplace}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

```

**Comment by rdcolema** [comment]
Hey Pavitrakumar, agreed that you shouldn't be running into any issues with 12GB -- what batch size and image sizes are you using? 

From your traceback it looks like we're using the same float type, and given that you're not using cnmem I don't think it should be an issue with anything in theano config. 

Only other thing I can think of is that I've set all the layers up to the last conv layer not to be trainable when I construct the model in `models.py` -- this reduces the number of parameters drastically, so if you're not using that step, that could explain the extra memory use.

Also occasionally when I get GPU memory errors that I shouldn't be getting, just killing the python process and restarting will clear it up, but I'm guessing you've already tried that. 

Regarding your question about `train` and `train_full` , the former is what I use when I separate out a validation set, whereas the latter includes all the training images -- no difference other than that.

**Comment by pavitrakumar78** [comment]
Hi rdcolema,

Thank you for your reply.

I have not changed the image size (using just the original photos) - maybe that is the problem. Should I resize them all to the size specified in the code? I have not changed the batch size also (same as in your original code).

I have not changed anything in models.py code and am using the same code as in your repo without any modifications. 

I have tried restarting/clearing processes - but its the same error every time.

**Comment by rdcolema** [comment]
You can specify a smaller image size when you instantiate the ` Vgg16BN` class, and you can try decreasing the batch size in the hyperparameters section. You could also change the number of nodes in the fully connected layers to something less than 4096. 

If none of that works it might be an unrelated cuda or theano issue -- might be worth confirming you can use the gpu on another task with similar memory requirements. 

For example, you could try using one of Keras' prepackaged [models](https://keras.io/applications/) and run that on a (224, 224) resizing of some of the sample fish images to confirm that everything is working properly. 

Hope that helps.

**Comment by pavitrakumar78** [comment]
Thank you for the suggestions rdcolema. 

Sorry I could not reply sooner.

I have tried your suggestions and got the code working in my local PC (NVIDIA GTX 660 2GB VRAM) itself. I halved the number of nodes in the `Dense` layers and reduced the image size to (100, 100) (parameter to VGGBN class).
But I wonder how the default parameters worked on an 8GB GPU but not on a 12 GB GPU. :confused: 

**Edit 1:** had a doubt regarding CNN pre-trained weights; resolved it by myself.

**Edit 2:** Just launched an p2.xlarge instance to test out the modifications; The change I made was - used 2048 Dense units instead of 4096. Kept images sizes same as the ones in the code. Memory usage was 9.7/11.4 GB VRAM.
Library versions (python 2.7):
Keras 1.2.1
numpy 1.12
theano 0.9
Are your libraries the same versions as above?
My theanorc file:
```
[global]
floatX = float32
device = gpu0
allow_gc = False

[nvcc]
fastmath = True

[cuda]
root = /usr/local/cuda-8.0

[blas]
ldflags = -lf77blas -latlas -lgfortran

[lib]
cnmem = 0
```

**Edit 3:** After letting it run for some time on the instance, the accuracy seems to peak at 40% and stays there. :(  I reverted the `Dense` layer nodes to 4096 (no change in models.py) and changed the input image size to 220,430 (anything higher gives me an out of memory error). Any idea why I am getting very different results from what you have posted in your notebooks?

**Comment by rdcolema** [comment]
Here's what's in my .theanorc:

```
[global]
floatX = float32
device = gpu0

[nvcc]
flags=-D_FORCE_INLINE

[lib]
cnmem = 0.9
```

And my package versions:

Theano==0.9.0.dev5
Keras==1.1.1
numpy==1.12.0

Python 3.5.2

**Comment by rdcolema** [comment]
One other note on accuracy being stuck at 40% -- the .001 learning rate that's currently set in the notebook is actually way too low for the Adadelta optimizer that VGG uses -- that's a leftover from using Adam with other architectures. That should be set closer to 1.0 for better results, and next time I update the repo I'll make that clearer.

**Comment by pavitrakumar78** [comment]
Thank you! I got it working - accuracy is good now. But I am still not able to run on K80 with the original image size on the same GPU :/ and we have no clue as to why that is the case.
